project:
  type: website

website:
  title: "Learning, Thinking, and Coding"
  site-url: https://brianrepko.github.io/blog
  description: "Brian Repko's blog"
  favicon: favicon.ico
  navbar:
    right:
      - icon: house-fill
        href: https://www.learnthinkcode.com/
      - icon: github
        href: https://github.com/brianrepko/blog/
      - icon: mastodon
        href: https://hachyderm.io/@brianrepko
      - icon: linkedin
        href: https://www.linkedin.com/in/brianrepko/
      - icon: rss
        href: index.xml

format:
  html:
    theme:
      - sandstone
      - brand
    css: styles.css
    link-external-icon: true
    link-external-newwindow: true



